server:
  port: 8084

spring:
  application:
    name: API-GATEWAY

  config:
    import: optional:configserver:http://localhost:8080

  cloud:
    config:
      username: Abhishek
      password: Abhishek
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**

        - id: HOTEL-SERVICE
          uri: lb://HOTEL-SERVICE
          predicates:
            - Path=/hotel/**

        - id: RATING-SERVICE
          uri: lb://RATING-SERVICE
          predicates:
            - Path=/rating/**