server:
  port: 8084

spring:
  application:
    name: API-GATEWAY

  config:
    import: optional:configserver:http://localhost:8080

  cloud:
    config:
      username: ConfigServer
      password: ConfigServer
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/** , /auth/**

        - id: HOTEL-SERVICE
          uri: lb://HOTEL-SERVICE
          predicates:
            - Path=/hotel/**
          filters:
            - name: AuthFilter

        - id: RATING-SERVICE
          uri: lb://RATING-SERVICE
          predicates:
            - Path=/rating/**
          filters:
            - name: AuthFilter

jwtKey: 416as541ca4d8c14c46v4fv49f8419ws1r99c1sv91881cv98w1cv891v1ev9e8v4e98v14e91s56vfs