spring:
  application:
   name: CONFIG-SERVER

  cloud:
    config:
      server:
       git:
         uri: https://github.com/wizzy-abhishek/micro-service----hotel-management
         clone-on-start: true

server:
  port: 8080